@echo off
echo Compiling generated tests source files...
javac -cp "%~dp0\../../../libs\*" "%~dp0\src/test/java//generated/GeneratedTests.java"
echo Running generated tests...
java -cp "%~dp0\../../../libs\*";"%~dp0\src/test/java/" org.testng.TestNG testng.xml